In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv("sri1.csv")

In [ ]:
for i in range(0,len(dataset['SRI'])):
  if(dataset['SRI'][i]==0):
    dataset['SRI'][i]=(1-(dataset['speed'][i])/23)*10

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
dataset.tail()

       Unnamed: 0  stop_id_from  ...  number_of_trips        SRI
13244       13244          1319  ...              1.0   2.181818
13245       13245          1104  ...              1.0   2.978723
13246       13246          1106  ...              1.0   7.076923
13247       13247         39593  ...              1.0 -20.898350
13248       13248         39385  ...              NaN   1.691428

[5 rows x 8 columns]

In [ ]:
dataset['Degree_of_congestion']=''

In [ ]:
for i in range(0,len(dataset['SRI'])):
  if(float(dataset['SRI'][i])<=0):
    dataset['Degree_of_congestion'][i]='Very smooth'
  elif((float(dataset['SRI'][i])>0) & (float(dataset['SRI'][i])<=2.5)):
    dataset['Degree_of_congestion'][i]='Smooth'  
  elif((float(dataset['SRI'][i])>2.5) & (float(dataset['SRI'][i])<=5)):
    dataset['Degree_of_congestion'][i]='Mild congestion'
  else:
    dataset['Degree_of_congestion'][i]='Heavy congestion'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [ ]:
if(float(dataset['SRI'][0])<=0):
    dataset['Degree_of_congestion']='Very smooth'

In [ ]:
dataset

       Unnamed: 0  stop_id_from  ...        SRI Degree_of_congestion
0               0          1117  ...   2.151899               Smooth
1               1          1117  ...   2.051282               Smooth
2               2          1115  ...   3.781512      Mild congestion
3               3          1115  ...   3.565217      Mild congestion
4               4          1111  ...   2.363636               Smooth
...           ...           ...  ...        ...                  ...
13244       13244          1319  ...   2.181818               Smooth
13245       13245          1104  ...   2.978723      Mild congestion
13246       13246          1106  ...   7.076923     Heavy congestion
13247       13247         39593  ... -20.898350          Very smooth
13248       13248         39385  ...   1.691428               Smooth

[13249 rows x 9 columns]

In [ ]:
stop_times = pd.read_csv('18.20mins_slot.csv')

In [ ]:
dataset['arrival_time']=''

In [ ]:
for i in range(11898,len(dataset['SRI'])):
  for j in range(0,len(stop_times['stop_id'])):
    if((dataset['stop_id_from'][i]==stop_times['stop_id'][j]) & (dataset['trip_id'][i]==stop_times['trip_id'][j])):
      dataset['arrival_time'][i] = stop_times['arrival_time'][j]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
dataset

       Unnamed: 0  stop_id_from  ...  Degree_of_congestion arrival_time
0               0          1117  ...                Smooth     18:10:36
1               1          1117  ...                Smooth     18:07:55
2               2          1115  ...       Mild congestion     18:12:26
3               3          1115  ...       Mild congestion     18:09:36
4               4          1111  ...                Smooth     18:00:01
...           ...           ...  ...                   ...          ...
13244       13244          1319  ...                Smooth     18:01:44
13245       13245          1104  ...       Mild congestion     18:02:53
13246       13246          1106  ...      Heavy congestion     18:03:50
13247       13247         39593  ...           Very smooth     18:06:00
13248       13248         39385  ...                Smooth     18:06:26

[13249 rows x 10 columns]

In [ ]:
dataset.to_csv('final_18-18_20.csv')