In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('FinalSlot4.csv')

In [ ]:
dataset.shape

(400755, 7)

In [ ]:
dataset.drop_duplicates(subset =['trip_id_modified','stop_id_modified_from','stop_id_modified_to'], inplace = True)

In [ ]:
dataset.shape

(39292, 7)

In [ ]:
dataset.to_csv('unique3.csv')

In [ ]:
dataset

        Unnamed: 0 route_id_modified  ... time_modified      speed
0                0            100_18  ...      0.056944   6.921938
1                1            100_18  ...      0.039722   9.923058
2                2            100_18  ...      0.056944   6.921938
3                3            100_18  ...      0.040556   9.719160
4                4            100_18  ...      0.064167   6.142846
...            ...               ...  ...           ...        ...
400502      400502              VJR6  ...      0.016389  25.723938
400503      400503              VJR6  ...      0.015000  35.131427
400504      400504              VJR6  ...      0.015000  35.131427
400505      400505              VJR6  ...      0.014444  24.245018
400506      400506              VJR6  ...      0.014444  24.245018

[39292 rows x 7 columns]

In [ ]:
read = pd.read_csv('unique3.csv')

In [ ]:
read

       Unnamed: 0  Unnamed: 0.1  ... time_modified      speed
0               0             0  ...      0.056944   6.921938
1               1             1  ...      0.039722   9.923058
2               2             2  ...      0.056944   6.921938
3               3             3  ...      0.040556   9.719160
4               4             4  ...      0.064167   6.142846
...           ...           ...  ...           ...        ...
39287      400502        400502  ...      0.016389  25.723938
39288      400503        400503  ...      0.015000  35.131427
39289      400504        400504  ...      0.015000  35.131427
39290      400505        400505  ...      0.014444  24.245018
39291      400506        400506  ...      0.014444  24.245018

[39292 rows x 8 columns]

In [ ]:
read.drop_duplicates(subset =['stop_id_modified_to','stop_id_modified_from'], inplace = True)

In [ ]:
read.to_csv('pll.csv')

In [ ]:
s = pd.read_csv('pll.csv')

In [ ]:
s

      Unnamed: 0  Unnamed: 0.1  ...  time_modified      speed
0              0             0  ...       0.056944   6.921938
1             25            25  ...       0.022222  26.632734
2             93            93  ...       0.020000  37.598869
3            149           149  ...       0.023889  19.862204
4            225           225  ...       0.008333  35.107451
...          ...           ...  ...            ...        ...
5828       39285        400397  ...       0.004167  61.590705
5829       39286        400398  ...       0.020833  20.383696
5830       39287        400502  ...       0.016389  25.723938
5831       39288        400503  ...       0.015000  35.131427
5832       39290        400505  ...       0.014444  24.245018

[5833 rows x 9 columns]

In [ ]:
u = pd.read_csv('unique3.csv')

In [ ]:
u

       Unnamed: 0  Unnamed: 0.1  ... time_modified      speed
0               0             0  ...      0.056944   6.921938
1               1             1  ...      0.039722   9.923058
2               2             2  ...      0.056944   6.921938
3               3             3  ...      0.040556   9.719160
4               4             4  ...      0.064167   6.142846
...           ...           ...  ...           ...        ...
39287      400502        400502  ...      0.016389  25.723938
39288      400503        400503  ...      0.015000  35.131427
39289      400504        400504  ...      0.015000  35.131427
39290      400505        400505  ...      0.014444  24.245018
39291      400506        400506  ...      0.014444  24.245018

[39292 rows x 8 columns]

In [ ]:
count = 0

In [ ]:
stop_id_from = []
stop_id_to = []

In [ ]:
len(u['stop_id_modified_from'])-1

39291

In [ ]:
count = 0

In [ ]:
df = pd.DataFrame

In [ ]:
l =[]

In [ ]:
for i in range(0,len(s['stop_id_modified_from'])-1):
  for j in range(0,len(u['stop_id_modified_from'])-1):
    if((s['stop_id_modified_from'][i]==u['stop_id_modified_from'][j]) and (s['stop_id_modified_to'][i]==u['stop_id_modified_to'][j])):
      count +=1
  l.append(count)    
  count = 0

KeyboardInterrupt: ignored

In [ ]:
l

[25,
 68,
 56,
 76,
 76,
 57,
 37,
 41,
 52,
 51,
 50,
 50,
 53,
 60,
 34,
 31,
 32,
 6,
 6,
 7,
 7,
 9,
 12,
 10,
 13,
 10,
 22,
 29,
 30,
 29,
 30,
 29,
 29,
 28,
 28,
 22,
 21,
 25,
 35,
 36,
 30,
 30,
 34,
 13,
 13,
 35,
 34,
 35,
 35,
 64,
 72,
 76,
 76,
 3,
 4,
 11,
 12,
 17,
 26,
 28,
 4,
 4,
 79,
 10,
 12,
 1,
 1,
 4,
 4,
 4,
 12,
 12,
 12,
 13,
 1,
 1,
 1,
 1,
 21,
 21,
 29,
 24,
 7,
 6,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 26,
 74,
 17,
 18,
 9,
 8,
 8,
 17,
 27,
 3,
 1,
 1,
 20,
 8,
 8,
 5,
 7,
 7,
 8,
 1,
 18,
 21,
 24,
 52,
 58,
 42,
 41,
 58,
 59,
 82,
 79,
 53,
 12,
 25,
 15,
 14,
 19,
 12,
 13,
 75,
 75,
 77,
 71,
 39,
 40,
 38,
 28,
 5,
 7,
 8,
 7,
 42,
 39,
 35,
 37,
 34,
 35,
 41,
 40,
 31,
 29,
 35,
 33,
 1,
 1,
 9,
 25,
 1,
 2,
 1,
 4,
 4,
 2,
 2,
 34,
 33,
 3,
 2,
 32,
 31,
 29,
 24,
 10,
 10,
 3,
 3,
 4,
 6,
 12,
 15,
 1,
 15,
 16,
 4,
 21,
 22,
 22,
 16,
 7,
 13,
 12,
 2,
 6,
 8,
 6,
 5,
 4,
 1,
 1,
 1,
 1,
 6,
 1,
 1,
 1,
 1,
 1,
 1,
 30,
 31,
 26,
 23,
 7,
 6,
 10,
 12,
 13,
 12,
 11,
 2,
 2,
 3,
 3,
 1,
 3,
 3,
 1,
 5,
 1,
 3,
 3,
 9,
 71,
 17,
 5,
 11,
 9,
 14,
 1,
 32,
 58,
 39,
 13,
 23,
 30,
 31,
 23,
 16,
 16,
 62,
 2,
 4,
 4,
 5,
 6,
 5,
 5,
 5,
 8,
 1,
 1,
 1,
 4,
 8,
 6,
 33,
 24,
 23,
 31,
 1,
 1,
 27,
 15,
 49,
 40,
 38,
 41,
 48,
 37,
 19,
 25,
 15,
 45,
 61,
 7,
 8,
 17,
 29,
 30,
 44,
 10,
 64,
 44,
 17,
 19,
 3,
 2,
 2,
 2,
 2,
 2,
 4,
 23,
 16,
 13,
 5,
 4,
 12,
 2,
 2,
 2,
 2,
 17,
 14,
 6,
 4,
 10,
 13,
 13,
 12,
 12,
 13,
 13,
 5,
 4,
 3,
 3,
 3,
 2,
 18,
 13,
 10,
 12,
 3,
 3,
 27,
 29,
 34,
 33,
 33,
 33,
 31,
 2,
 4,
 21,
 9,
 9,
 16,
 17,
 16,
 4,
 3,
 24,
 29,
 9,
 8,
 16,
 26,
 14,
 19,
 32,
 1,
 2,
 9,
 9,
 8,
 8,
 7,
 19,
 23,
 3,
 30,
 10,
 9,
 30,
 31,
 5,
 1,
 12,
 5,
 2,
 3,
 7,
 1,
 1,
 1,
 1,
 8,
 34,
 47,
 55,
 57,
 57,
 57,
 13,
 8,
 8,
 13,
 7,
 19,
 23,
 23,
 22,
 22,
 10,
 12,
 23,
 23,
 22,
 22,
 8,
 9,
 24,
 21,
 21,
 23,
 23,
 12,
 23,
 25,
 25,
 25,
 25,
 23,
 23,
 22,
 23,
 24,
 26,
 22,
 10,
 6,
 14,
 10,
 34,
 19,
 29,
 29,
 39,
 3,
 4,
 4,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 6,
 4,
 5,
 7,
 9,
 9,
 9,
 9,
 9,
 10,
 12,
 10,
 9,
 10,
 9,
 9,
 9,
 8,
 7,
 7,
 8,
 8,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 8,
 7,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 2,
 3,
 5,
 2,
 15,
 40,
 38,
 38,
 38,
 40,
 27,
 28,
 53,
 55,
 56,
 55,
 16,
 23,
 25,
 23,
 24,
 5,
 5,
 5,
 29,
 8,
 40,
 29,
 30,
 30,
 26,
 29,
 34,
 4,
 4,
 20,
 20,
 13,
 3,
 3,
 1,
 24,
 24,
 24,
 21,
 26,
 26,
 29,
 1,
 1,
 3,
 3,
 1,
 5,
 5,
 8,
 8,
 8,
 7,
 7,
 8,
 3,
 3,
 3,
 1,
 3,
 11,
 15,
 11,
 9,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 26,
 4,
 4,
 4,
 1,
 2,
 2,
 12,
 1,
 4,
 4,
 3,
 4,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 3,
 3,
 1,
 1,
 2,
 28,
 5,
 5,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 17,
 15,
 21,
 2,
 2,
 15,
 15,
 15,
 12,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 8,
 8,
 8,
 8,
 9,
 8,
 7,
 6,
 6,
 6,
 6,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 2,
 12,
 1,
 1,
 1,
 1,
 1,
 124,
 141,
 1,
 4,
 14,
 20,
 22,
 22,
 21,
 23,
 23,
 5,
 5,
 13,
 12,
 2,
 2,
 6,
 7,
 15,
 3,
 3,
 3,
 2,
 4,
 4,
 1,
 16,
 15,
 30,
 7,
 18,
 2,
 1,
 1,
 6,
 3,
 19,
 19,
 19,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 18,
 49,
 7,
 7,
 59,
 60,
 34,
 32,
 33,
 36,
 35,
 33,
 32,
 27,
 10,
 10,
 6,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 16,
 17,
 16,
 10,
 9,
 9,
 20,
 19,
 18,
 17,
 16,
 17,
 11,
 1,
 1,
 1,
 1,
 1,
 17,
 18,
 16,
 22,
 16,
 3,
 11,
 16,
 11,
 4,
 3,
 11,
 12,
 1,
 1,
 13,
 6,
 6,
 7,
 7,
 7,
 12,
 8,
 6,
 5,
 6,
 7,
 7,
 5,
 12,
 24,
 54,
 5,
 10,
 10,
 5,
 5,
 8,
 8,
 6,
 6,
 7,
 4,
 5,
 5,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 27,
 1,
 4,
 4,
 3,
 3,
 6,
 5,
 5,
 5,
 8,
 9,
 9,
 3,
 1,
 9,
 5,
 1,
 8,
 7,
 15,
 3,
 6,
 6,
 6,
 5,
 5,
 2,
 2,
 2,
 2,
 1,
 27,
 27,
 27,
 26,
 17,
 29,
 31,
 24,
 19,
 17,
 3,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 14,
 10,
 5,
 4,
 3,
 7,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 5,
 5,
 1,
 6,
 2,
 4,
 4,
 1,
 8,
 3,
 4,
 4,
 6,
 7,
 4,
 4,
 4,
 4,
 4,
 1,
 5,
 6,
 3,
 3,
 2,
 2,
 2,
 1,
 3,
 4,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 14,
 25,
 26,
 24,
 25,
 25,
 19,
 55,
 30,
 33,
 10,
 12,
 7,
 10,
 10,
 10,
 19,
 9,
 10,
 4,
 4,
 1,
 12,
 12,
 12,
 11,
 11,
 10,
 11,
 11,
 12,
 11,
 11,
 4,
 19,
 21,
 22,
 32,
 34,
 37,
 4,
 4,
 6,
 12,
 5,
 5,
 11,
 4,
 4,
 ...]

In [ ]:
number_of_trips = pd.DataFrame(l)

In [ ]:
number_of_trips

         0
0      2.0
1      2.0
2      2.0
3      2.0
4      2.0
...    ...
6485  21.0
6486  21.0
6487  21.0
6488  21.0
6489  21.0

[6490 rows x 1 columns]

In [ ]:
number_of_trips.to_csv('count3.csv')

In [ ]:
dataset = pd.read_csv('summary_18-18.20.csv')

In [ ]:
dataset

        stop_id_modified_from  stop_id_modified_to  time_modified  no_of_trips
0                      1117.0               1115.0       0.021944          2.0
1                      1115.0               1111.0       0.021667          2.0
2                      1111.0               1109.0       0.033056          2.0
3                      1109.0              39395.0       0.031944          2.0
4                     39395.0              39394.0       0.015278          2.0
...                       ...                  ...            ...          ...
313358                    NaN                  NaN       0.013056          NaN
313359                    NaN                  NaN       0.013889          NaN
313360                    NaN                  NaN       0.002222          NaN
313361                    NaN                  NaN       0.000556          NaN
313362                    NaN                  NaN       0.000556          NaN

[313363 rows x 4 columns]

In [ ]:
len(dataset['no_of_trips'])

313363

In [ ]:
df = dataset['no_of_trips'].dropna()

In [ ]:
len(df)

3245

In [ ]:
len(dataset['no_of_trips'])

313363

In [ ]:
l = df.tolist()

In [ ]:
l

[2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 13.0,
 13.0,
 13.0,
 21.0,
 19.0,
 19.0,
 20.0,
 20.0,
 19.0,
 10.0,
 17.0,
 30.0,
 30.0,
 21.0,
 14.0,
 17.0,
 5.0,
 8.0,
 26.0,
 17.0,
 27.0,
 26.0,
 19.0,
 11.0,
 15.0,
 18.0,
 16.0,
 15.0,
 14.0,
 13.0,
 18.0,
 11.0,
 11.0,
 11.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 2.0,
 5.0,
 5.0,
 7.0,
 13.0,
 14.0,
 14.0,
 13.0,
 11.0,
 10.0,
 8.0,
 9.0,
 9.0,
 10.0,
 7.0,
 3.0,
 3.0,
 11.0,
 9.0,
 9.0,
 10.0,
 11.0,
 15.0,
 14.0,
 12.0,
 13.0,
 10.0,
 9.0,
 13.0,
 1.0,
 1.0,
 1.0,
 5.0,
 6.0,
 5.0,
 4.0,
 6.0,
 6.0,
 6.0,
 5.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 4.0,
 2.0,
 36.0,
 11.0,
 12.0,
 11.0,
 11.0,
 12.0,
 6.0,
 5.0,
 12.0,
 12.0,
 11.0,
 10.0,
 18.0,
 22.0,
 22.0,
 23.0,
 2.0,
 2.0,
 3.0,
 2.0,
 3.0,
 6.0,
 9.0,
 2.0,
 2.0,
 36.0,
 2.0,
 2.0,
 37.0,
 1.0,
 2.0,
 5.0,
 3.0,
 28.0,
 29.0,
 25.0,
 18.0,
 6.0,
 9.0,
 9.0,
 12.0,
 11.0,
 8.0,
 9.0,
 9.0,
 9.0,
 10.0,
 11.0,
 10.0,
 5.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 9.0,
 16.0,
 9.0,
 8.0,
 2.0,
 3.0,
 3.0,
 7.0,
 8.0,
 1.0,
 9.0,
 2.0,
 1.0,
 2.0,
 2.0,
 2.0,
 6.0,
 5.0,
 5.0,
 20.0,
 21.0,
 2.0,
 2.0,
 4.0,
 1.0,
 6.0,
 2.0,
 2.0,
 1.0,
 2.0,
 26.0,
 21.0,
 35.0,
 38.0,
 4.0,
 1.0,
 1.0,
 21.0,
 24.0,
 19.0,
 24.0,
 29.0,
 22.0,
 12.0,
 14.0,
 10.0,
 7.0,
 1.0,
 5.0,
 10.0,
 3.0,
 4.0,
 18.0,
 24.0,
 19.0,
 19.0,
 27.0,
 1.0,
 1.0,
 5.0,
 1.0,
 4.0,
 3.0,
 2.0,
 1.0,
 1.0,
 1.0,
 4.0,
 3.0,
 2.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 3.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 3.0,
 3.0,
 1.0,
 6.0,
 3.0,
 3.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 11.0,
 13.0,
 12.0,
 5.0,
 8.0,
 1.0,
 1.0,
 2.0,
 10.0,
 9.0,
 1.0,
 1.0,
 10.0,
 10.0,
 11.0,
 5.0,
 3.0,
 3.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 10.0,
 6.0,
 9.0,
 10.0,
 9.0,
 11.0,
 9.0,
 9.0,
 11.0,
 11.0,
 1.0,
 7.0,
 7.0,
 3.0,
 3.0,
 4.0,
 2.0,
 1.0,
 10.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 7.0,
 4.0,
 1.0,
 3.0,
 3.0,
 4.0,
 4.0,
 4.0,
 2.0,
 1.0,
 4.0,
 4.0,
 4.0,
 5.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 3.0,
 1.0,
 1.0,
 2.0,
 22.0,
 4.0,
 1.0,
 2.0,
 3.0,
 1.0,
 12.0,
 10.0,
 7.0,
 10.0,
 9.0,
 9.0,
 8.0,
 3.0,
 18.0,
 20.0,
 12.0,
 18.0,
 14.0,
 3.0,
 8.0,
 10.0,
 10.0,
 9.0,
 5.0,
 4.0,
 3.0,
 1.0,
 1.0,
 1.0,
 3.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 3.0,
 1.0,
 3.0,
 1.0,
 3.0,
 17.0,
 3.0,
 9.0,
 7.0,
 4.0,
 2.0,
 1.0,
 5.0,
 7.0,
 6.0,
 13.0,
 20.0,
 22.0,
 18.0,
 21.0,
 21.0,
 25.0,
 19.0,
 16.0,
 14.0,
 16.0,
 22.0,
 16.0,
 10.0,
 13.0,
 2.0,
 2.0,
 4.0,
 7.0,
 8.0,
 2.0,
 11.0,
 7.0,
 7.0,
 10.0,
 1.0,
 8.0,
 7.0,
 16.0,
 3.0,
 17.0,
 4.0,
 13.0,
 9.0,
 8.0,
 11.0,
 7.0,
 11.0,
 5.0,
 3.0,
 1.0,
 8.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 8.0,
 7.0,
 7.0,
 2.0,
 1.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 1.0,
 2.0,
 5.0,
 8.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 4.0,
 4.0,
 3.0,
 4.0,
 6.0,
 6.0,
 5.0,
 14.0,
 15.0,
 1.0,
 20.0,
 19.0,
 9.0,
 1.0,
 1.0,
 9.0,
 8.0,
 7.0,
 5.0,
 1.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 3.0,
 3.0,
 3.0,
 3.0,
 4.0,
 3.0,
 3.0,
 2.0,
 1.0,
 1.0,
 3.0,
 4.0,
 3.0,
 3.0,
 3.0,
 4.0,
 4.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 1.0,
 2.0,
 6.0,
 6.0,
 6.0,
 9.0,
 9.0,
 6.0,
 7.0,
 6.0,
 8.0,
 10.0,
 9.0,
 1.0,
 3.0,
 2.0,
 9.0,
 9.0,
 1.0,
 2.0,
 8.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 2.0,
 3.0,
 7.0,
 1.0,
 6.0,
 5.0,
 7.0,
 1.0,
 1.0,
 1.0,
 1.0,
 13.0,
 11.0,
 10.0,
 11.0,
 5.0,
 8.0,
 3.0,
 3.0,
 4.0,
 6.0,
 3.0,
 5.0,
 8.0,
 9.0,
 1.0,
 2.0,
 3.0,
 1.0,
 1.0,
 1.0,
 10.0,
 1.0,
 14.0,
 3.0,
 4.0,
 21.0,
 18.0,
 3.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 7.0,
 7.0,
 7.0,
 8.0,
 5.0,
 2.0,
 6.0,
 2.0,
 3.0,
 1.0,
 16.0,
 15.0,
 15.0,
 16.0,
 2.0,
 2.0,
 4.0,
 3.0,
 4.0,
 4.0,
 7.0,
 6.0,
 6.0,
 6.0,
 7.0,
 7.0,
 5.0,
 5.0,
 2.0,
 5.0,
 5.0,
 5.0,
 3.0,
 6.0,
 6.0,
 6.0,
 6.0,
 6.0,
 7.0,
 7.0,
 5.0,
 6.0,
 4.0,
 7.0,
 5.0,
 3.0,
 7.0,
 6.0,
 6.0,
 6.0,
 3.0,
 4.0,
 6.0,
 6.0,
 19.0,
 20.0,
 21.0,
 21.0,
 4.0,
 3.0,
 3.0,
 7.0,
 4.0,
 6.0,
 8.0,
 7.0,
 9.0,
 9.0,
 3.0,
 13.0,
 7.0,
 8.0,
 7.0,
 7.0,
 7.0,
 6.0,
 7.0,
 6.0,
 6.0,
 5.0,
 5.0,
 13.0,
 1.0,
 2.0,
 2.0,
 3.0,
 3.0,
 4.0,
 5.0,
 14.0,
 6.0,
 5.0,
 2.0,
 1.0,
 5.0,
 8.0,
 2.0,
 1.0,
 3.0,
 2.0,
 1.0,
 2.0,
 3.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 4.0,
 4.0,
 3.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 2.0,
 2.0,
 3.0,
 4.0,
 4.0,
 2.0,
 3.0,
 3.0,
 3.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 3.0,
 3.0,
 3.0,
 2.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 7.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 5.0,
 15.0,
 17.0,
 18.0,
 12.0,
 18.0,
 18.0,
 17.0,
 17.0,
 4.0,
 7.0,
 7.0,
 7.0,
 9.0,
 3.0,
 3.0,
 1.0,
 1.0,
 4.0,
 15.0,
 16.0,
 16.0,
 8.0,
 5.0,
 14.0,
 14.0,
 14.0,
 12.0,
 2.0,
 2.0,
 1.0,
 8.0,
 9.0,
 12.0,
 11.0,
 5.0,
 15.0,
 4.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 7.0,
 4.0,
 3.0,
 10.0,
 9.0,
 9.0,
 8.0,
 8.0,
 9.0,
 9.0,
 6.0,
 8.0,
 8.0,
 7.0,
 9.0,
 11.0,
 1.0,
 1.0,
 6.0,
 6.0,
 3.0,
 2.0,
 2.0,
 11.0,
 10.0,
 7.0,
 9.0,
 10.0,
 8.0,
 6.0,
 4.0,
 8.0,
 9.0,
 7.0,
 6.0,
 7.0,
 8.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 4.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 6.0,
 1.0,
 1.0,
 2.0,
 1.0,
 3.0,
 1.0,
 1.0,
 5.0,
 6.0,
 7.0,
 7.0,
 6.0,
 7.0,
 7.0,
 1.0,
 1.0,
 5.0,
 2.0,
 1.0,
 6.0,
 6.0,
 6.0,
 6.0,
 9.0,
 8.0,
 8.0,
 7.0,
 8.0,
 9.0,
 6.0,
 3.0,
 1.0,
 6.0,
 7.0,
 10.0,
 4.0,
 7.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 3.0,
 1.0,
 1.0,
 1.0,
 1.0,
 7.0,
 5.0,
 20.0,
 14.0,
 1.0,
 8.0,
 12.0,
 12.0,
 11.0,
 12.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 16.0,
 13.0,
 14.0,
 12.0,
 11.0,
 12.0,
 9.0,
 10.0,
 5.0,
 5.0,
 ...]

In [ ]:
time_mean = []

In [ ]:
sum = 0
dummy_sum = 0

In [ ]:
dataset.head(5)

   stop_id_modified_from  stop_id_modified_to  time_modified  no_of_trips
0                 1117.0               1115.0       0.021944          2.0
1                 1115.0               1111.0       0.021667          2.0
2                 1111.0               1109.0       0.033056          2.0
3                 1109.0              39395.0       0.031944          2.0
4                39395.0              39394.0       0.015278          2.0

In [ ]:
for i in l:
    dummy_sum += i
    for j in range(0,int(dummy_sum)):
      sum += dataset['time_modified'][j]
    time_mean.append(sum)  
    sum = 0

In [ ]:
time_mean

[0.043611111,
 0.108611111,
 0.139166667,
 0.19305555500000002,
 0.22305555500000002,
 0.23638888800000002,
 0.269166666,
 0.44944444300000014,
 0.631111109,
 0.9294444409999997,
 1.2986111109999994,
 1.725833332999999,
 1.9319444459999988,
 2.021944446999999,
 2.242500001999999,
 2.453888891999999,
 3.1425000029999985,
 3.5544444489999987,
 3.936111115,
 4.165277780000004,
 4.778611113000005,
 5.548888890000004,
 5.905555556000004,
 6.229166667000004,
 6.568888890000005,
 7.387777780000006,
 7.847777779000006,
 8.570000002000008,
 8.809444446000002,
 8.890277780999996,
 9.379166670999998,
 9.630555561000001,
 9.757222226000001,
 9.935000003000004,
 10.014444446000002,
 10.163333335999999,
 10.546666670999995,
 10.714722226999998,
 11.01444445,
 11.185833339,
 11.376111115999997,
 11.435833337999997,
 11.458611115999997,
 11.474444448999996,
 11.501944448999996,
 11.534722225999996,
 11.593333336999995,
 11.635000002999996,
 11.720833336999998,
 11.978611114999998,
 12.200277781999997,
 12.420000005999997,
 12.573611114999999,
 12.681666668999997,
 12.977500004999998,
 13.489722227999998,
 13.755277784,
 13.986388896,
 14.216388895,
 14.518888895,
 14.795555562,
 14.947777784000001,
 15.001388895000002,
 15.081666673000003,
 15.345833340000002,
 15.430000005999998,
 15.515000005999996,
 15.572500006999995,
 15.626666673999992,
 16.14500000899999,
 16.37888889899999,
 16.465000009999986,
 16.58305556299998,
 16.688055562999978,
 16.73777778499998,
 16.860000006999986,
 16.865833339999988,
 16.87166667299999,
 16.88222222899999,
 16.96250000799999,
 17.137500008999986,
 17.29500000899999,
 17.33250000799999,
 17.390277785999995,
 17.446666675999992,
 17.57305556499999,
 17.71472223199999,
 17.737500009999987,
 17.762777787999987,
 17.778611120999987,
 17.794444453999986,
 17.810833342999988,
 17.870277786999985,
 17.906111120999984,
 18.60861111899999,
 19.01138889599999,
 19.575833340999985,
 19.866666674999983,
 20.16611111999998,
 20.565000007999974,
 20.68222222999997,
 20.792500007999966,
 21.105000007999966,
 21.421944452999963,
 21.52666667499997,
 21.61750000799997,
 21.710277786999978,
 22.32916667799997,
 22.56472223399997,
 22.783611119999964,
 22.794166675999964,
 22.80611111999996,
 22.823888897999964,
 22.834722230999965,
 22.848888896999966,
 22.927500008999964,
 23.056944451999957,
 23.09138889599996,
 23.118611117999958,
 23.78638889699995,
 23.82055556399995,
 23.86111111999995,
 24.488333342999958,
 24.500000009999958,
 24.516666676999957,
 24.538333342999962,
 24.553333342999967,
 24.788888898999968,
 25.419722233999977,
 26.169444456999962,
 26.36500001199996,
 26.508611123999962,
 26.57583334499996,
 26.64333334399996,
 26.73833334399995,
 27.036666677999957,
 27.274444455999955,
 27.701944455999957,
 28.14916667699996,
 28.353888898999966,
 28.625000008999965,
 28.94583334299996,
 29.06500000899996,
 29.170000007999963,
 29.219444451999966,
 29.268333340999966,
 29.292777784999966,
 29.303055562999965,
 29.319722229999964,
 29.332222229999964,
 29.342222229999965,
 29.356666673999964,
 29.376111117999965,
 29.47750000699997,
 29.73000000999997,
 30.079166676999975,
 30.258333343999983,
 30.300277787999985,
 30.361388898999984,
 30.40527778799998,
 30.496666676999975,
 30.616666675999976,
 30.631111119999975,
 30.766944452999976,
 30.813611118999976,
 30.832500007999975,
 30.873888896999976,
 30.932500007999973,
 30.97833334099997,
 31.09555556299997,
 31.18305556399997,
 31.26805556599997,
 31.651944454999974,
 31.978055566999974,
 32.000833344999975,
 32.024166678999975,
 32.04222223399997,
 32.047222233999975,
 32.075277789999966,
 32.08305556799996,
 32.090000012999965,
 32.095833345999964,
 32.10583334599997,
 32.374722234999986,
 32.87027779199999,
 33.78416668099999,
 34.18972223400001,
 34.22833334500001,
 34.23638890100001,
 34.244444457000014,
 34.834166680000024,
 35.82972223400002,
 36.494722233000005,
 36.89305556500001,
 37.43083334400002,
 37.80250000800004,
 37.96083334100004,
 38.10805556500005,
 38.48694445500004,
 38.668333345000036,
 38.70027778900003,
 38.79972223300003,
 38.95277778900004,
 38.99611112200004,
 39.055833343000046,
 39.350833342000044,
 39.81222223300004,
 40.21277778900006,
 40.47750001200007,
 40.64750001300006,
 40.65722223500006,
 40.66833334600006,
 40.724722235000065,
 40.736666679000066,
 40.778333346000075,
 40.811388902000076,
 40.83416668000008,
 40.84472223600008,
 40.85444445800008,
 40.86527779100008,
 40.905833347000076,
 40.95111112400008,
 40.97333334700008,
 41.00444445800009,
 41.01611112500009,
 41.025000014000085,
 41.03527779200009,
 41.04555557000009,
 41.12833334800009,
 41.17833334800009,
 41.20722223700009,
 41.313333348000086,
 41.509722237000084,
 41.73416668100008,
 41.75805557000008,
 41.78194445900008,
 41.82222223700008,
 41.843055570000075,
 41.866944459000074,
 41.91694445900007,
 41.94611112600007,
 42.01527779300007,
 42.09777779300007,
 42.12194446000007,
 42.18138890400008,
 42.211666682000086,
 42.22972223700008,
 42.276666682000084,
 42.29333334800008,
 42.325000015000086,
 42.331388904000086,
 42.337777793000086,
 42.35250001500009,
 42.36083334800009,
 42.541666681000095,
 42.6419444580001,
 42.735833346000106,
 42.79166668100011,
 43.048611125000114,
 43.111111125000114,
 43.12750001400011,
 43.160277792000116,
 43.560555569000115,
 44.03722223500011,
 44.08555556800011,
 44.14055556800011,
 44.365833346000116,
 44.6369444560001,
 45.0647222330001,
 45.1383333440001,
 45.191944455000105,
 45.228888899000104,
 45.257777788000105,
 45.29361112200011,
 45.31166667800011,
 45.32611112200011,
 45.340555566000106,
 45.35750001000011,
 45.57833334300011,
 45.69083334300011,
 45.84111112200011,
 45.984444455000116,
 46.08666667600012,
 46.33111112000014,
 46.45055556400013,
 46.54583334300014,
 46.78166667800014,
 47.13472223400013,
 47.16777779000013,
 47.31416667800013,
 47.424722234000136,
 47.46666667800013,
 47.511388900000135,
 47.56833334400014,
 47.60277778800014,
 47.61555556600014,
 47.76583334300014,
 47.81250000900013,
 47.831388898000135,
 47.85027778700014,
 47.87277778700014,
 47.90222223100014,
 47.93138889800014,
 47.953333342000136,
 47.977222231000134,
 48.10944445300013,
 48.18194445400013,
 48.197500010000134,
 48.24916667800014,
 48.297777789000136,
 48.37250001200014,
 48.45694445700014,
 48.53250001200014,
 48.568611123000146,
 48.58583334500015,
 48.67583334500015,
 48.79583334500015,
 48.846388901000154,
 48.90166667900016,
 48.92222223500016,
 48.948888902000164,
 48.957500013000164,
 48.968333346000165,
 48.976944457000165,
 48.98694445700016,
 48.99972223500016,
 49.011388902000164,
 49.023055569000164,
 49.028055569000166,
 49.032777791000164,
 49.04111112400016,
 49.04611112400016,
 49.04972223500016,
 49.05444445700016,
 49.05916667900016,
 49.064722235000154,
 49.074166680000154,
 49.08194445800015,
 49.098611125000154,
 49.12138890300016,
 49.28638890300016,
 49.35694445800016,
 49.41555556900016,
 49.470277791000164,
 49.484166680000165,
 49.49722223600016,
 49.521111124000164,
 49.965277790000165,
 50.03805556800017,
 50.053333346000166,
 50.085833346000165,
 50.13333334700017,
 50.147500014000165,
 50.31083334600017,
 50.48694445600019,
 50.6233333450002,
 50.752500011000194,
 50.8516666790002,
 51.0211111250002,
 51.35777779200019,
 51.40527779200019,
 51.7611111260002,
 51.99583334700021,
 52.0877777900002,
 52.4630555700002,
 52.65472223600021,
 52.68166668100021,
 52.76500001500022,
 52.93055557100023,
 53.088888904000235,
 53.25416668200024,
 53.35972223700025,
 53.397777792000255,
 53.42472223700026,
 53.43388890400026,
 53.44388890400026,
 53.45944446000026,
 53.51194446100026,
 53.54111112800026,
 53.57083335100026,
 53.599166685000256,
 53.634722241000254,
 53.66888890700026,
 53.696388907000255,
 53.83388890700026,
 53.84472224000026,
 53.88916668400026,
 53.91722224000026,
 53.94833335100026,
 53.97805557300026,
 54.01777779500026,
 54.04472224000026,
 54.06861112800026,
 54.13333335100027,
 54.15138890700027,
 54.19722223900027,
 54.21472223900027,
 54.27722223900027,
 54.618055572000266,
 54.664166684000264,
 54.79888890600027,
 54.880277795000275,
 54.92638890500028,
 54.973333349000285,
 55.008611127000286,
 55.13138890400029,
 55.227500015000295,
 55.30000001500029,
 55.4466666830003,
 55.850555572000324,
 56.415555574000344,
 56.60916668300035,
 56.92555557200035,
 57.250277794000354,
 57.58500001800037,
 57.922222240000394,
 58.13277779700041,
 58.450555576000404,
 58.72250002000041,
 59.080277797000406,
 59.230277798000394,
 59.65277779900039,
 59.871111133000404,
 59.89416668900041,
 59.908611133000406,
 59.93861113300041,
 59.98638891100041,
 60.05444446500041,
 60.080000020000405,
 60.19583335300041,
 60.234444464000404,
 60.270555574000404,
 60.379444463000404,
 60.390000019000404,
 60.55722224300041,
 60.77333335500042,
 60.942500022000424,
 60.97083335500043,
 61.362500021000436,
 61.42694446700044,
 61.661944466000456,
 61.81722224300047,
 61.97694446500048,
 62.42638891000048,
 62.564722243000496,
 62.725555578000495,
 62.7780555770005,
 62.80972224300051,
 62.819722243000506,
 62.8888889090005,
 62.8955555760005,
 62.9036111320005,
 62.9097222430005,
 62.916944465000505,
 62.9308333530005,
 63.1052777980005,
 63.251666689000494,
 63.3619444660005,
 63.3944444660005,
 63.4058333550005,
 63.449444465000504,
 63.4638889090005,
 63.4747222420005,
 63.483888909000505,
 63.494444465000505,
 63.50472224300051,
 63.513611132000506,
 63.523611132000504,
 63.54805557700051,
 63.55666668800051,
 63.57694446600051,
 63.64722224400052,
 63.780555578000524,
 63.811666689000525,
 63.82916668900052,
 63.843888911000526,
 63.861388911000525,
 63.876388911000525,
 63.93888891100053,
 64.00111113300053,
 64.06694446700054,
 64.14527780000053,
 64.23805557700051,
 64.29388891100051,
 64.3769444680005,
 64.7452778040005,
 65.28833336000048,
 65.31361113800048,
 65.84000002600045,
 66.41083336000042,
 66.61472224900041,
 66.64027780500041,
 66.6880555830004,
 66.8788889160004,
 66.95361113800041,
 67.0133333600004,
 67.06444447100039,
 67.07250002700039,
 67.09083336000037,
 67.09750002700038,
 67.10250002700037,
 67.10750002700038,
 67.11527780500039,
 67.12694447200039,
 67.14055558300039,
 67.1497222500004,
 67.15722225000039,
 67.1658333620004,
 67.25555558400039,
 67.3797222510004,
 67.57083336200041,
 67.67805558500042,
 67.72638891800042,
 67.76055558500042,
 67.77611114100041,
 67.79250003000041,
 67.84111114100041,
 67.9119444750004,
 67.93388891900038,
 67.95527780800037,
 67.97777780800037,
 68.00444447500034,
 68.03166669600033,
 68.03861114000033,
 68.05055558400032,
 68.05972225100032,
 68.06972225100033,
 68.07972225100033,
 68.09305558400034,
 68.12750002800034,
 68.14250002800034,
 68.16277780600034,
 68.22111113900034,
 68.25305558300033,
 68.28777780500032,
 68.38194447200033,
 68.49555558400033,
 68.67055558500034,
 68.84833336200032,
 68.90416669500031,
 68.97972225200031,
 69.2194444750003,
 69.38777780700033,
 69.40333336300033,
 69.45222225300031,
 69.48555558600032,
 69.64222225200031,
 69.79916669600031,
 69.81611114000032,
 69.87472225100032,
 70.07694447300031,
 70.26000002900031,
 70.42333336300031,
 70.53472225200031,
 70.6247222520003,
 70.70138892000028,
 70.72500003100028,
 70.75916669700027,
 70.83500002900026,
 70.84500002900026,
 70.89888891700026,
 70.93500002900026,
 71.03361113900026,
 71.05861113900026,
 71.08222225000026,
 71.10888891700026,
 71.13055558400026,
 71.37222225200027,
 71.51972225100029,
 71.61277780800029,
 71.79083336400028,
 71.86916669700028,
 71.99638891900028,
 72.04916669700029,
 72.11083336400029,
 72.19166669700027,
 72.27305558500025,
 72.30000003000025,
 72.36166669800025,
 72.48722225600024,
 72.69222225600026,
 72.70472225600027,
 72.73055559000026,
 72.77694447900026,
 72.79166670100027,
 72.81750003400026,
 72.82416670100027,
 73.00916670200026,
 73.02722225800025,
 73.26194448100024,
 73.30138892500024,
 73.39250003500024,
 73.89194448100022,
 74.27805559100021,
 74.32722225700022,
 74.35944448000022,
 74.38583336900022,
 74.38777781300023,
 74.38944448000022,
 74.39083336900022,
 74.39277781300022,
 74.39416670200022,
 74.40750003500021,
 74.4113889240002,
 74.4136111460002,
 74.4241667020002,
 74.43222225800021,
 74.43916670200021,
 74.44472225800021,
 74.45027781400022,
 74.51333337000023,
 74.65666670300023,
 74.75777781400024,
 74.89833337000022,
 74.93166670300022,
 74.93888892500021,
 74.9794444800002,
 74.9963889250002,
 75.0191667030002,
 75.03111114700019,
 75.26638892500019,
 75.39805559200019,
 75.7119444790002,
 76.42833336800021,
 76.52500003400021,
 76.62944447800021,
 76.7130555890002,
 76.75055558800021,
 76.80888892200021,
 76.8566667000002,
 76.93944447700022,
 77.0583333660002,
 77.14666670000021,
 77.2738889230002,
 77.38027781200019,
 77.4419444800002,
 77.48611114700022,
 77.53277781400023,
 77.55333337000022,
 77.67416670300021,
 77.79111114800021,
 77.8913889250002,
 78.0713889250002,
 78.30055559200022,
 78.49277781300022,
 78.58972225800021,
 78.6919444810002,
 78.81416670400021,
 78.9066667040002,
 78.99944448300022,
 79.09722226100023,
 79.20916670500021,
 79.33194448300023,
 79.42000003900024,
 79.50166670600024,
 79.55916670600023,
 79.71361115200023,
 79.83833337400023,
 79.98083337400021,
 80.10611115200022,
 80.15861115100023,
 80.24833337300022,
 80.34444448400023,
 80.43638892800024,
 80.69027781900029,
 81.07000004300029,
 81.47861115300032,
 82.04388893300032,
 82.10500004400033,
 82.14500004400034,
 82.21666671100034,
 82.44888893300036,
 82.52166671000037,
 82.65750004300035,
 82.78888893300037,
 82.88388893200036,
 83.08861115300036,
 83.33861115300036,
 83.39138893000036,
 83.71888892900036,
 83.95166670800035,
 84.17305559700034,
 84.31777781800037,
 84.43444448400038,
 84.5047222610004,
 84.56694448300038,
 84.64083337200037,
 84.6758333720004,
 84.71694448400038,
 84.74750003900037,
 84.81333337200039,
 84.99638892600039,
 85.0133333700004,
 85.0486111480004,
 85.0825000370004,
 85.1675000360004,
 85.2166667030004,
 85.27861114700039,
 85.3763889240004,
 85.57888892200039,
 85.73277781100039,
 85.94388892200038,
 86.05777781100038,
 86.11388892200038,
 86.4069444780004,
 86.6916666990004,
 86.7183333650004,
 86.7291666980004,
 86.7708333650004,
 86.80055558800039,
 86.8116666990004,
 86.83527781000039,
 86.86527781000039,
 86.8908333650004,
 86.9044444760004,
 86.91805558700041,
 86.9255555870004,
 86.9522222540004,
 86.9722222540004,
 86.9922222540004,
 87.01694447600039,
 87.03694447600039,
 87.05472225400038,
 87.06611114300038,
 87.07750003200039,
 87.1252778100004,
 87.2169444770004,
 87.28055558800038,
 87.34333336600038,
 87.35888892200038,
 87.37583336700038,
 87.39861114500039,
 87.41250003400039,
 87.42055559000039,
 87.43666670100039,
 87.4522222570004,
 87.47361114600041,
 87.48638892400041,
 87.52444448000041,
 87.57555559100041,
 87.73750003500041,
 87.8319444790004,
 87.9672222560004,
 88.0997222560004,
 88.22388892200041,
 88.26583336600041,
 88.33611114400041,
 88.36555558900041,
 88.4127778110004,
 88.45027781100039,
 88.48277781100037,
 88.50777781100037,
 88.52055558900037,
 88.61555558900037,
 89.12944447800037,
 89.55805558900038,
 90.15361114400038,
 90.56638892200037,
 90.69666669900037,
 90.93138892100038,
 90.99472225400038,
 91.04972225400039,
 91.08972225400039,
 91.13277781000039,
 91.14805558800039,
 91.18166669900039,
 91.24333336500038,
 91.28000003200039,
 91.32222225400038,
 91.36333336500037,
 91.40861114300036,
 91.46083336500035,
 91.50583336400035,
 91.76305558500036,
 91.84805558600036,
 92.08500003200034,
 92.16361114200032,
 92.34722225300031,
 92.52972225300032,
 92.85805558500033,
 93.60138891800034,
 93.80250002800034,
 93.92361113800034,
 94.01361113900033,
 94.09888891600035,
 94.26055558300033,
 94.30805558300034,
 94.36222225000034,
 94.38888891700034,
 94.41138891700034,
 94.47500002800032,
 94.63666669700034,
 94.87472225500034,
 95.19083336700032,
 95.34250003500031,
 95.39472225700034,
 95.63500003600035,
 95.99111114800036,
 96.34694448300036,
 96.60694448300039,
 96.6850000380004,
 96.7405555940004,
 96.7550000380004,
 96.9266667040004,
 97.0805555940004,
 97.28333337000039,
 97.5616667030004,
 97.6830555910004,
 98.06416670200039,
 98.22194448000039,
 98.24333336900038,
 98.28250003600037,
 98.30750003600038,
 98.34750003600038,
 98.37611114700039,
 98.39833336900038,
 98.49194448000038,
 98.6383333680004,
 98.7038889230004,
 98.73500003400042,
 98.84250003300042,
 98.93250003300041,
 98.98777781100041,
 99.03916670000041,
 99.1938889220004,
 99.31638892100038,
 99.47944447600038,
 99.56527780900038,
 99.81944447600036,
 99.94861114200037,
 100.02722225400038,
 100.1127778100004,
 100.53611114400037,
 100.68861114400038,
 100.76916670000037,
 101.12250003400038,
 101.41055559000038,
 101.50750003400039,
 101.53138892200037,
 101.55416670000037,
 101.75027781300037,
 101.88527781200037,
 102.01138892300037,
 102.14333336800037,
 102.32055559000037,
 102.40583336800036,
 102.49166670200036,
 102.57166670300035,
 102.92500003700034,
 103.41111114900035,
 103.75138892500036,
 103.83805559100036,
 103.92805559200035,
 104.02694448000037,
 104.03444448000036,
 104.06111114700036,
 104.08111114700036,
 104.10111114700035,
 104.12583336900035,
 104.14583336900034,
 104.16361114700034,
 104.17500003600034,
 104.18638892500034,
 104.21361114700035,
 104.22250003600035,
 104.25500003600035,
 104.27666670300036,
 104.30333337000036,
 104.32583337000035,
 104.34361114800035,
 104.37222225900034,
 104.41611114800034,
 104.45222225900034,
 104.45972225900033,
 104.46777781500033,
 104.47583337100033,
 104.48472226000034,
 104.49944448200034,
 104.50750003800034,
 104.51472226000034,
 104.52138892700034,
 104.52944448300035,
 104.53638892700035,
 104.54555559400035,
 104.55111115000035,
 104.56111115000036,
 104.57361115000036,
 104.58250003900037,
 104.59000003900036,
 104.59527781700037,
 104.60777781700037,
 104.62027781700037,
 104.65833337300036,
 104.75083337300036,
 104.76861115000035,
 104.81277781700035,
 104.82333337300035,
 104.87333337300035,
 104.88305559500034,
 104.90805559500035,
 104.93138892800036,
 104.94888892800036,
 104.98388892800035,
 105.09388892800037,
 105.23305559400036,
 105.24166670500036,
 105.27000003800036,
 105.30750003800036,
 105.34694448200035,
 105.36000003800035,
 105.36611114900035,
 105.37222226000034,
 105.38305559300034,
 105.39722226000033,
 105.43166670500032,
 105.44638892700033,
 105.54694448400032,
 105.57416670600033,
 105.58694448400033,
 105.63333337300033,
 105.65611115100033,
 105.70055559600033,
 105.70805559600032,
 105.71750004000032,
 105.78083337400032,
 105.88166670800034,
 106.04944448500034,
 106.20666670800034,
 106.34444448600036,
 106.51722226400037,
 106.62888893100036,
 106.64305559800036,
 106.66083337600035,
 106.75611115500034,
 106.78777782100035,
 106.80500004300035,
 106.90972226600033,
 107.10083337800033,
 107.28638893400033,
 107.49916671100033,
 107.72305559900033,
 107.94583337800034,
 108.16694448900034,
 108.31250004200034,
 108.4588889320003,
 108.67361115500027,
 108.79083337800026,
 108.94527782300025,
 108.97805560100025,
 109.27666671300024,
 109.57111115700025,
 109.84944449100024,
 109.87722226900024,
 110.09305560300025,
 110.11361115900026,
 110.16861115900026,
 110.22361115900027,
 110.26333338100027,
 110.30166671400026,
 110.36277782500026,
 110.37138893600026,
 110.39972226900026,
 110.43722226900026,
 110.47666671300026,
 110.48305560200025,
 110.49222226900025,
 110.50472226900025,
 110.51166671300025,
 110.51916671300025,
 110.52527782400024,
 110.56861115800022,
 110.58138893600022,
 110.59361115800023,
 110.60444449100022,
 110.61722226900022,
 110.71888893600021,
 110.80750004800021,
 111.17277782800019,
 111.3716667180002,
 111.3819444960002,
 111.5911111620002,
 111.87555560700022,
 112.10111116300023,
 112.29500005300021,
 112.59083338800019,
 112.60944449900019,
 112.64250005500018,
 112.67361116600019,
 112.73750005500018,

In [ ]:
wrong_time = pd.DataFrame(time_mean)

In [ ]:
len(wrong_time)

3245

In [ ]:
wrong_time

               0
0       0.043611
1       0.108611
2       0.139167
3       0.193056
4       0.223056
...          ...
3240  252.884167
3241  252.914722
3242  252.926667
3243  252.952500
3244  252.966945

[3245 rows x 1 columns]

In [ ]:
wrong_time.to_csv('time_Extra4.csv')

In [ ]:
avg = pd.read_csv('time_Extra4.csv')

In [ ]:
avg

      Unnamed: 0    time_sum
0              0    0.043611
1              1    0.108611
2              2    0.139167
3              3    0.193056
4              4    0.223056
...          ...         ...
3240        3240  252.884167
3241        3241  252.914722
3242        3242  252.926667
3243        3243  252.952500
3244        3244  252.966945

[3245 rows x 2 columns]

In [ ]:
avg['time_sum']

0         0.043611
1         0.108611
2         0.139167
3         0.193056
4         0.223056
           ...
3240    252.884167
3241    252.914722
3242    252.926667
3243    252.952500
3244    252.966945
Name: time_sum, Length: 3245, dtype: float64

In [ ]:
avg['avg_time'] = avg['time_sum'].diff()

In [ ]:
avg

      Unnamed: 0    time_sum  avg_time
0              0    0.043611       NaN
1              1    0.108611  0.065000
2              2    0.139167  0.030556
3              3    0.193056  0.053889
4              4    0.223056  0.030000
...          ...         ...       ...
3240        3240  252.884167  0.028333
3241        3241  252.914722  0.030556
3242        3242  252.926667  0.011944
3243        3243  252.952500  0.025833
3244        3244  252.966945  0.014444

[3245 rows x 3 columns]

In [ ]:
avg['avg_time'][0] = avg['time_sum'][0]

In [ ]:
dataset

        stop_id_modified_from  stop_id_modified_to  time_modified  no_of_trips
0                      1117.0               1115.0       0.021944          2.0
1                      1115.0               1111.0       0.021667          2.0
2                      1111.0               1109.0       0.033056          2.0
3                      1109.0              39395.0       0.031944          2.0
4                     39395.0              39394.0       0.015278          2.0
...                       ...                  ...            ...          ...
313358                    NaN                  NaN       0.013056          NaN
313359                    NaN                  NaN       0.013889          NaN
313360                    NaN                  NaN       0.002222          NaN
313361                    NaN                  NaN       0.000556          NaN
313362                    NaN                  NaN       0.000556          NaN

[313363 rows x 4 columns]

In [ ]:
avg['trip'] = dataset['no_of_trips']

In [ ]:
avg

      Unnamed: 0    time_sum  avg_time  trip
0              0    0.043611  0.043611   2.0
1              1    0.108611  0.065000   2.0
2              2    0.139167  0.030556   2.0
3              3    0.193056  0.053889   2.0
4              4    0.223056  0.030000   2.0
...          ...         ...       ...   ...
3240        3240  252.884167  0.028333   1.0
3241        3241  252.914722  0.030556   1.0
3242        3242  252.926667  0.011944   1.0
3243        3243  252.952500  0.025833   1.0
3244        3244  252.966945  0.014444   1.0

[3245 rows x 4 columns]

In [ ]:
avg['average_time'] = avg['avg_time']/avg['trip']

In [ ]:
avg

      Unnamed: 0    time_sum  avg_time  trip  average_time
0              0    0.043611  0.043611   2.0      0.021806
1              1    0.108611  0.065000   2.0      0.032500
2              2    0.139167  0.030556   2.0      0.015278
3              3    0.193056  0.053889   2.0      0.026944
4              4    0.223056  0.030000   2.0      0.015000
...          ...         ...       ...   ...           ...
3240        3240  252.884167  0.028333   1.0      0.028333
3241        3241  252.914722  0.030556   1.0      0.030556
3242        3242  252.926667  0.011944   1.0      0.011944
3243        3243  252.952500  0.025833   1.0      0.025833
3244        3244  252.966945  0.014444   1.0      0.014444

[3245 rows x 5 columns]

In [ ]:
avg.to_csv('average_time_3.csv')